spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=never

#JWT Key
jwt.secret=E9jyklrexjyu8qKRBEZB5DWvI/1MbYlEE8SS6LqVLq9l3y7T0S21+8T2vQl22mII7GLYlCJGo1gxio+h/5Pzxw==