spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://tramway.proxy.rlwy.net:59940/railway}

spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASS:xTOXxfcseCGNLqJgOHtOZNcjEZlubCOx}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never

#JWT Key
jwt.secret=E9jyklrexjyu8qKRBEZB5DWvI/1MbYlEE8SS6LqVLq9l3y7T0S21+8T2vQl22mII7GLYlCJGo1gxio+h/5Pzxw==