spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d2moj4p5pdvs73947vpg-a.oregon-postgres.render.com:5432/zupasvpetar

spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.username=zupasvpetar_user
spring.datasource.password=3ECMj6He3EzT5d18Lv5MxWOvwstdjzJf

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

#JWT Key
jwt.secret=E9jyklrexjyu8qKRBEZB5DWvI/1MbYlEE8SS6LqVLq9l3y7T0S21+8T2vQl22mII7GLYlCJGo1gxio+h/5Pzxw==