INSERT INTO Category (name) VALUES ('Povijest župe');
INSERT INTO Category (name) VALUES ('Sv. Petar');
INSERT INTO Category (name) VALUES ('Raspored bogoslužja');
INSERT INTO Category (name) VALUES ('Župna kateheza za odrasle');
INSERT INTO Category (name) VALUES ('Dječji zbor');
INSERT INTO Category (name) VALUES ('Župni pjevački zbor');
INSERT INTO Category (name) VALUES ('Župno pastoralno i ekonomsko vijeće');
INSERT INTO Category (name) VALUES ('Pobožnosti');
INSERT INTO Category (name) VALUES ('Krštenje');
INSERT INTO Category (name) VALUES ('Sveta Pričest');
INSERT INTO Category (name) VALUES ('Sveta Potvrda');
INSERT INTO Category (name) VALUES ('Euharistija');
INSERT INTO Category (name) VALUES ('Ispovijed');
INSERT INTO Category (name) VALUES ('Bolesničko pomazanje');
INSERT INTO Category (name) VALUES ('Ženidba');
INSERT INTO Category (name) VALUES ('Sveti red');
INSERT INTO Category (name) VALUES ('Blagoslov obitelji');
INSERT INTO Category (name) VALUES ('Sprovod');
INSERT INTO Category (name) VALUES ('Hodočašća');
INSERT INTO Category (name) VALUES ('Župni Caritas');
INSERT INTO Category (name) VALUES ('Ministranti');
